name: 'Setup Google Cloud'
description: 'Checkout code, authenticate and set up Google Cloud SDK'
inputs:
  credentials_json:
    description: 'JSON credentials for Google Cloud'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        version: 'latest'
        service_account_key: ${{ inputs.credentials_json }}
        export_default_credentials: true