version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - my_network
    environment:
      REDIS_PASSWORD: redis_images
    command: /bin/sh -c "redis-server --requirepass $REDIS_PASSWORD"
  
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network
    volumes:
      - /rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  particionador:
    image: grupo4sdypp2024/tp4-h1-particionador_requeue
    container_name: "particionador"
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - my_network

  unificador:
    image: grupo4sdypp2024/tp4-h2-unificador
    container_name: "unificador"
    ports:
      - "5002:5002"
    depends_on:
      - particionador
    networks:
      - my_network
    environment:
      REDIS_PASSWORD: redis_images

  server:
    image: grupo4sdypp2024/tp4-h1-server
    container_name: "server"
    ports:
      - "5000:5000"
    depends_on:
      - particionador
      - unificador
    networks:
      - my_network

