apiVersion: apps/v1
kind: Deployment
metadata:
  name: particionador
  labels:
    app: particionador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: particionador
  template:
    metadata:
      labels:
        app: particionador
    spec:
      containers:
      - name: particionador
        image: grupo4sdypp2024/tp4-h2-particionador
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        ports:
        - containerPort: 5001