apiVersion: apps/v1
kind: Deployment
metadata:
  name: particionador
  labels:
    app: particionador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: particionador
  template:
    metadata:
      labels:
        app: particionador
    spec:
      containers:
      - name: particionador
        image: grupo4sdypp2024/tp4-h3-particionador
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: particionador
spec:
  ports:
  - port: 5001
  selector:
    app: particionador
  type: ClusterIP
