apiVersion: apps/v1
kind: Deployment
metadata:
  name: unificador
  labels:
    app: unificador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unificador
  template:
    metadata:
      labels:
        app: unificador
    spec:
      containers:
      - name: unificador
        image: grupo4sdypp2024/tp4-h2-unificador
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: unificador
spec:
  ports:
  - port: 5002
  selector:
    app: unificador
  type: ClusterIP