name: Deploy Applications

on:
  workflow_dispatch:

jobs:
  deploy-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push blocks coordinator service image
        uses: docker/build-push-action@v5
        with:
            context: ./TP-Integrador/Coordinator
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-integrador-coordinator:1.0.0

      - name: Build and push pool manager service image
        uses: docker/build-push-action@v5
        with:
            context: ./TP-Integrador/KeepAliveServer
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-integrador-pool-manager:1.0.0

      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
            context: ./TP-Integrador/Worker/CPU
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-integrador-cpu-worker:1.0.0

      - name: Setup Google Cloud
        uses: ./.github/actions/gcloud-credentials
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Get Kubernetes Credentials
        run: |
          gcloud container clusters get-credentials primary --zone "us-east1-b" --project ${{ secrets.PROJECT_ID }}

    #   - name: Create Kubernetes Apps
    #     run: |
    #       kubectl apply -f TP-Integrador/apps/particionador/particionador-deployment.yaml
    #       kubectl apply -f TP-Integrador/apps/particionador/particionador-service.yaml
    #       kubectl apply -f TP-Integrador/apps/unificador/unificador-deployment.yaml
    #       kubectl apply -f TP-Integrador/apps/unificador/unificador-service.yaml
    #       kubectl apply -f TP-Integrador/apps/web-server/web-server-deployment.yaml
    #       kubectl apply -f TP-Integrador/apps/web-server/web-server-service.yaml
