name: Deploy Services

on:
  workflow_dispatch:

jobs:
  deploy-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Setup Google Cloud
        uses: ./.github/actions/gcloud-credentials
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Get Kubernetes Credentials
        run: |
          gcloud container clusters get-credentials primary --zone "us-east1-b" --project ${{ secrets.PROJECT_ID }}

      - name: Create Kubernetes Services
        run: |
          kubectl apply -f TP4/H3/servicios/rabbitmq/rabbitmq-deployment.yaml
          kubectl apply -f TP4/H3/servicios/rabbitmq/rabbitmq-service.yaml
          kubectl apply -f TP4/H3/servicios/redis/redis-deployment.yaml
          kubectl apply -f TP4/H3/servicios/redis/redis-service.yaml

      - name: Trigger Next Pipeline
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-apps.yml',
              ref: 'main'
            })